"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";

type Store = { id: string; name: string };
type Member = { id: string; email: string; role: string; joinedAt: string; storeIds: string[] };
const roles: Record<string, string> = { OWNER: "所有者", ADMIN: "管理员", BOOKKEEPER: "记账员", VIEWER: "查看者" };

export function ManagementPanel({ organization, currentMemberId, role, initialStores }: { organization: { id: string; name: string }; currentMemberId: string; role: string; initialStores: Store[] }) {
  const [members, setMembers] = useState<Member[]>([]); const [stores, setStores] = useState(initialStores); const [loading, setLoading] = useState(true); const [message, setMessage] = useState("");
  const [editing, setEditing] = useState<Member | null>(null); const [removing, setRemoving] = useState<Member | null>(null); const [renaming, setRenaming] = useState<Store | null>(null); const [adding, setAdding] = useState(false);
  const canManage = role === "OWNER";
  const loadMembers = useCallback(async () => { setLoading(true); try { const response = await fetch(`/api/organizations/current/members?organizationId=${organization.id}`); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error?.message ?? "成员加载失败"); setMembers(result.members); } catch (error) { setMessage(error instanceof Error ? error.message : "成员加载失败，请稍后重试。"); } finally { setLoading(false); } }, [organization.id]);
  useEffect(() => { const timer = window.setTimeout(() => void loadMembers(), 0); return () => window.clearTimeout(timer); }, [loadMembers]);
  function done(text: string) { setEditing(null); setRemoving(null); setRenaming(null); setAdding(false); setMessage(text); void loadMembers(); }
  return <main className="app-shell management-shell"><header className="records-header"><div><p className="eyebrow">{organization.name}</p><h1>成员与摊位</h1></div><Link className="ghost records-home" href="/">返回首页</Link></header>
    {!canManage && <p className="notice neutral">当前权限为{roles[role]}，成员和摊位信息仅供查看。</p>}{message && <p className={message.includes("成功") ? "success-notice" : "notice"}>{message}</p>}
    <section className="management-section"><div className="management-title"><div><h2>成员</h2><span>{members.length} 人</span></div></div>{loading ? <p className="records-loading">正在加载成员…</p> : <div className="management-list">{members.map((member) => <article className="management-row" key={member.id}><div><strong>{member.email}{member.id === currentMemberId ? "（我）" : ""}</strong><p>{roles[member.role]} · {member.role === "OWNER" ? "全部摊位" : `${member.storeIds.length} 个摊位`}</p></div>{canManage && member.role !== "OWNER" && <div className="compact-actions"><button onClick={() => setEditing(member)}>编辑</button><button className="delete-link" onClick={() => setRemoving(member)}>移除</button></div>}</article>)}</div>}</section>
    <section className="management-section"><div className="management-title"><div><h2>摊位</h2><span>{stores.length} 个</span></div>{canManage && <button className="primary small-command" onClick={() => setAdding(true)}>新增摊位</button>}</div><div className="management-list">{stores.map((store) => <article className="management-row" key={store.id}><div><strong>{store.name}</strong><p>{members.filter((member) => member.role === "OWNER" || member.storeIds.includes(store.id)).length} 位成员可访问</p></div>{canManage && <button className="ghost" onClick={() => setRenaming(store)}>改名</button>}</article>)}</div></section>
    {editing && <MemberEditor member={editing} stores={stores} onClose={() => setEditing(null)} onSaved={() => done("成员权限更新成功。")} />}{removing && <ConfirmRemove member={removing} onClose={() => setRemoving(null)} onSaved={() => done("成员移除成功。")} />}{adding && <StoreEditor organizationId={organization.id} onClose={() => setAdding(false)} onSaved={(store) => { setStores((value) => [...value, store]); done("摊位创建成功。"); }} />}{renaming && <StoreEditor store={renaming} organizationId={organization.id} onClose={() => setRenaming(null)} onSaved={(store) => { setStores((value) => value.map((item) => item.id === store.id ? store : item)); done("摊位名称更新成功。"); }} />}
  </main>;
}

function MemberEditor({ member, stores, onClose, onSaved }: { member: Member; stores: Store[]; onClose: () => void; onSaved: () => void }) { const [role, setRole] = useState(member.role); const [selected, setSelected] = useState(member.storeIds); const [error, setError] = useState(""); const [pending, setPending] = useState(false); async function save() { setPending(true); setError(""); try { const response = await fetch(`/api/organization-members/${member.id}`, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ role, storeIds: selected }) }); const result = await response.json().catch(() => null); if (!response.ok) throw new Error(result?.error?.message ?? "保存失败"); onSaved(); } catch (e) { setError(e instanceof Error ? e.message : "保存失败，请重试。"); } finally { setPending(false); } } return <Modal title="编辑成员权限" onClose={onClose}><div className="form-stack"><p className="muted">{member.email}</p><label>角色<select value={role} onChange={(e) => setRole(e.target.value)}><option value="ADMIN">管理员</option><option value="BOOKKEEPER">记账员</option><option value="VIEWER">查看者</option></select></label><div className="field-label">授权摊位</div><div className="check-list">{stores.map((store) => <label key={store.id}><input type="checkbox" checked={selected.includes(store.id)} onChange={() => setSelected((ids) => ids.includes(store.id) ? ids.filter((id) => id !== store.id) : [...ids, store.id])} />{store.name}</label>)}</div>{error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={pending || !selected.length} onClick={save}>{pending ? "保存中…" : "保存成员权限"}</button></div></Modal>; }
function ConfirmRemove({ member, onClose, onSaved }: { member: Member; onClose: () => void; onSaved: () => void }) { const [error, setError] = useState(""); async function remove() { const response = await fetch(`/api/organization-members/${member.id}`, { method: "DELETE" }); const result = await response.json().catch(() => null); if (!response.ok) return setError(result?.error?.message ?? "移除失败"); onSaved(); } return <Modal title="确认移除成员" onClose={onClose}><p><strong>{member.email}</strong></p><p className="muted">移除后该成员无法继续访问家庭商户，已经记录的历史账目会保留。</p>{error && <p className="form-error">{error}</p>}<button className="danger wide" onClick={remove}>确认移除</button></Modal>; }
function StoreEditor({ organizationId, store, onClose, onSaved }: { organizationId: string; store?: Store; onClose: () => void; onSaved: (store: Store) => void }) { const [error, setError] = useState(""); const [pending, setPending] = useState(false); async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setPending(true); const name = String(new FormData(event.currentTarget).get("name")); const response = await fetch(store ? `/api/stores/${store.id}` : "/api/stores", { method: store ? "PATCH" : "POST", headers: { "Content-Type": "application/json" }, body: JSON.stringify(store ? { name } : { name, organizationId }) }); const result = await response.json().catch(() => null); setPending(false); if (!response.ok) return setError(result?.error?.message ?? "保存失败"); onSaved(result.store); } return <Modal title={store ? "修改摊位名称" : "新增摊位"} onClose={onClose}><form className="form-stack" onSubmit={submit}><label>摊位名称<input name="name" required maxLength={60} defaultValue={store?.name} autoFocus /></label>{!store && <p className="settings-tip">新摊位不会自动授权给其他成员，创建后可在成员列表中分配。</p>}{error && <p className="form-error">{error}</p>}<button className="primary wide" disabled={pending}>{pending ? "保存中…" : store ? "保存名称" : "创建摊位"}</button></form></Modal>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={title}><section className="modal"><header><h2>{title}</h2><button className="ghost" onClick={onClose}>关闭</button></header>{children}</section></div>; }
