"use client";
import Link from "next/link";
import { FormEvent, useCallback, useEffect, useState } from "react";
import { formatFen, yuanToFen } from "@/lib/money";

type Store = { id: string; name: string };
type Bootstrap = { organization: { id: string; name: string }; member: { role: string }; stores: Store[] };
type Entry = { id: string; type: "INCOME" | "EXPENSE"; amountFen: number; paymentMethod: string; category: string; occurredAt: string; note?: string | null; store: Store };
type Permissions = { canEdit: boolean; canDelete: boolean };
const methodLabel: Record<string, string> = { CASH: "现金", WECHAT: "微信", ALIPAY: "支付宝", BANK_CARD: "银行卡", OTHER: "其他" };
const chinaDate = (date: Date) => new Intl.DateTimeFormat("en-CA", { timeZone: "Asia/Shanghai", year: "numeric", month: "2-digit", day: "2-digit" }).format(date);
const shiftDate = (days: number) => { const date = new Date(); date.setDate(date.getDate() + days); return chinaDate(date); };
const toLocalInput = (value: string) => { const date = new Date(value); const local = new Date(date.getTime() - date.getTimezoneOffset() * 60_000); return local.toISOString().slice(0, 16); };

export function RecordsManager({ bootstrap }: { bootstrap: Bootstrap }) {
  const [storeId, setStoreId] = useState("all"); const [from, setFrom] = useState(shiftDate(-29)); const [to, setTo] = useState(chinaDate(new Date()));
  const [type, setType] = useState(""); const [paymentMethod, setPaymentMethod] = useState(""); const [entries, setEntries] = useState<Entry[]>([]);
  const [permissions, setPermissions] = useState<Permissions>({ canEdit: false, canDelete: false }); const [nextCursor, setNextCursor] = useState<string | null>(null);
  const [loading, setLoading] = useState(true); const [message, setMessage] = useState(""); const [editing, setEditing] = useState<Entry | null>(null); const [deleting, setDeleting] = useState<Entry | null>(null);
  const loadEntries = useCallback(async (cursor?: string) => {
    setLoading(true); setMessage(""); const params = new URLSearchParams({ organizationId: bootstrap.organization.id, storeId, from, to, limit: "50" });
    if (type) params.set("type", type); if (paymentMethod) params.set("paymentMethod", paymentMethod); if (cursor) params.set("cursor", cursor);
    try { const response = await fetch("/api/ledger-entries?" + params); const result = await response.json().catch(() => null); if (!response.ok) { setMessage(result?.error?.message ?? "账目加载失败，请稍后重试。"); return; } setEntries((current) => cursor ? [...current, ...result.entries] : result.entries); setNextCursor(result.nextCursor); setPermissions(result.permissions); }
    catch { setMessage("当前网络不可用，请联网后重试。"); } finally { setLoading(false); }
  }, [bootstrap.organization.id, storeId, from, to, type, paymentMethod]);
  useEffect(() => { const timer = window.setTimeout(() => void loadEntries(), 0); return () => window.clearTimeout(timer); }, [loadEntries]);
  function preset(days: number | "month") { const end = chinaDate(new Date()); setTo(end); setFrom(days === "month" ? end.slice(0, 8) + "01" : shiftDate(-(days - 1))); }
  function refreshAfterChange(text: string) { setEditing(null); setDeleting(null); void loadEntries().then(() => setMessage(text)); }
  return <main className="app-shell records-shell"><header className="records-header"><div><p className="eyebrow">{bootstrap.organization.name}</p><h1>账目</h1></div><Link className="ghost records-home" href="/">返回首页</Link></header>
    <section className="records-filters"><label>摊位<select value={storeId} onChange={(event) => setStoreId(event.target.value)}><option value="all">全部已授权摊位</option>{bootstrap.stores.map((store) => <option key={store.id} value={store.id}>{store.name}</option>)}</select></label><div className="record-presets"><button onClick={() => preset(1)}>今天</button><button onClick={() => preset(7)}>近 7 天</button><button onClick={() => preset(30)}>近 30 天</button><button onClick={() => preset("month")}>本月</button></div><div className="record-filter-grid"><label>开始日期<input type="date" value={from} max={to} onChange={(event) => setFrom(event.target.value)} /></label><label>结束日期<input type="date" value={to} min={from} max={chinaDate(new Date())} onChange={(event) => setTo(event.target.value)} /></label><label>收支类型<select value={type} onChange={(event) => setType(event.target.value)}><option value="">全部</option><option value="INCOME">收入</option><option value="EXPENSE">支出</option></select></label><label>收付款方式<select value={paymentMethod} onChange={(event) => setPaymentMethod(event.target.value)}><option value="">全部</option>{Object.entries(methodLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label></div></section>
    {message && <p className={message.includes("成功") ? "success-notice" : "notice"}>{message}</p>}<section className="records-list" aria-busy={loading}>{!loading && !entries.length ? <div className="records-empty"><strong>没有符合条件的账目</strong><span>可以调整日期或筛选条件再查看。</span></div> : entries.map((entry) => <article className="record-item" key={entry.id}><div className="record-main"><div><strong>{entry.category}</strong><p>{entry.store.name} · {methodLabel[entry.paymentMethod]} · {new Date(entry.occurredAt).toLocaleString("zh-CN", { month: "numeric", day: "numeric", hour: "2-digit", minute: "2-digit" })}</p>{entry.note && <small>{entry.note}</small>}</div><b className={entry.type === "INCOME" ? "positive" : "negative"}>{entry.type === "INCOME" ? "+" : "-"}{formatFen(entry.amountFen)}</b></div>{(permissions.canEdit || permissions.canDelete) && <div className="record-actions">{permissions.canEdit && <button onClick={() => setEditing(entry)}>编辑</button>}{permissions.canDelete && <button className="delete-link" onClick={() => setDeleting(entry)}>删除</button>}</div>}</article>)}{loading && <p className="records-loading">正在加载账目…</p>}</section>{nextCursor && !loading && <button className="load-more" onClick={() => void loadEntries(nextCursor)}>继续加载</button>}
    {editing && <EditEntryModal entry={editing} onClose={() => setEditing(null)} onSaved={() => refreshAfterChange("账目修改成功。")} />}{deleting && <DeleteEntryModal entry={deleting} onClose={() => setDeleting(null)} onDeleted={() => refreshAfterChange("账目删除成功。")} />}</main>;
}

function EditEntryModal({ entry, onClose, onSaved }: { entry: Entry; onClose: () => void; onSaved: () => void }) {
  const [entryType, setEntryType] = useState(entry.type); const [pending, setPending] = useState(false); const [message, setMessage] = useState("");
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); if (!navigator.onLine) { setMessage("编辑账目需要联网，请恢复网络后重试。"); return; } setPending(true); setMessage(""); const form = new FormData(event.currentTarget); try { const response = await fetch("/api/ledger-entries/" + entry.id, { method: "PATCH", headers: { "Content-Type": "application/json" }, body: JSON.stringify({ type: entryType, amountFen: yuanToFen(String(form.get("amount"))), paymentMethod: form.get("paymentMethod"), category: form.get("category"), occurredAt: new Date(String(form.get("occurredAt"))).toISOString(), note: form.get("note") || null }) }); const result = await response.json().catch(() => null); if (!response.ok) { setMessage(result?.error?.message ?? "修改失败，请稍后重试。"); return; } onSaved(); } catch (error) { setMessage(error instanceof Error ? error.message : "修改失败，请稍后重试。"); } finally { setPending(false); } }
  return <Modal title="编辑账目" onClose={onClose}><form className="form-stack" onSubmit={submit}><div className="segmented"><button type="button" className={entryType === "INCOME" ? "selected income" : ""} onClick={() => setEntryType("INCOME")}>收入</button><button type="button" className={entryType === "EXPENSE" ? "selected expense" : ""} onClick={() => setEntryType("EXPENSE")}>支出</button></div><label>金额（元）<input required inputMode="decimal" name="amount" defaultValue={(entry.amountFen / 100).toFixed(2)} /></label><label>收付款方式<select name="paymentMethod" defaultValue={entry.paymentMethod}>{Object.entries(methodLabel).map(([value, label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>分类<input required name="category" defaultValue={entry.category} /></label><label>发生时间<input required type="datetime-local" name="occurredAt" defaultValue={toLocalInput(entry.occurredAt)} /></label><label>备注（选填）<input name="note" defaultValue={entry.note ?? ""} /></label>{message && <p className="form-error">{message}</p>}<button className="primary wide" disabled={pending}>{pending ? "保存中…" : "保存修改"}</button></form></Modal>;
}
function DeleteEntryModal({ entry, onClose, onDeleted }: { entry: Entry; onClose: () => void; onDeleted: () => void }) { const [pending, setPending] = useState(false); const [message, setMessage] = useState(""); async function remove() { if (!navigator.onLine) { setMessage("删除账目需要联网，请恢复网络后重试。"); return; } setPending(true); try { const response = await fetch("/api/ledger-entries/" + entry.id, { method: "DELETE" }); const result = await response.json().catch(() => null); if (!response.ok) { setMessage(result?.error?.message ?? "删除失败，请稍后重试。"); return; } onDeleted(); } catch { setMessage("删除失败，请检查网络后重试。"); } finally { setPending(false); } } return <Modal title="确认删除账目" onClose={onClose}><div className="delete-summary"><strong>{entry.category}</strong><b className={entry.type === "INCOME" ? "positive" : "negative"}>{entry.type === "INCOME" ? "+" : "-"}{formatFen(entry.amountFen)}</b><span>{new Date(entry.occurredAt).toLocaleString("zh-CN")}</span></div><p className="muted">删除后这笔账目不会再计入经营统计。此操作不能在页面中撤销。</p>{message && <p className="form-error">{message}</p>}<button className="danger wide" onClick={remove} disabled={pending}>{pending ? "删除中…" : "确认删除"}</button></Modal>; }
function Modal({ title, children, onClose }: { title: string; children: React.ReactNode; onClose: () => void }) { return <div className="modal-backdrop" role="dialog" aria-modal="true" aria-label={title}><section className="modal"><header><h2>{title}</h2><button className="ghost" onClick={onClose}>关闭</button></header>{children}</section></div>; }
